// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	io "io"

	csv "github.com/William9923/bulk-upload-poc/pkg/csv"

	mock "github.com/stretchr/testify/mock"
)

// ICsvBuilder is an autogenerated mock type for the ICsvBuilder type
type ICsvBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: header, content
func (_m *ICsvBuilder) Build(header []string, content [][]string) csv.ICsv {
	ret := _m.Called(header, content)

	var r0 csv.ICsv
	if rf, ok := ret.Get(0).(func([]string, [][]string) csv.ICsv); ok {
		r0 = rf(header, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(csv.ICsv)
		}
	}

	return r0
}

// FromFile provides a mock function with given fields: file
func (_m *ICsvBuilder) FromFile(file io.Reader) (csv.ICsv, error) {
	ret := _m.Called(file)

	var r0 csv.ICsv
	if rf, ok := ret.Get(0).(func(io.Reader) csv.ICsv); ok {
		r0 = rf(file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(csv.ICsv)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
