// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IResponse is an autogenerated mock type for the IResponse type
type IResponse struct {
	mock.Mock
}

// Render provides a mock function with given fields: w
func (_m *IResponse) Render(w http.ResponseWriter) {
	_m.Called(w)
}

// SetData provides a mock function with given fields: data
func (_m *IResponse) SetData(data interface{}) {
	_m.Called(data)
}

// SetError provides a mock function with given fields: code, err
func (_m *IResponse) SetError(code int, err error) {
	_m.Called(code, err)
}
